name: flutter_advanced_course
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  #An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
  flutter_svg: ^2.2.3
  #A flutter plugin for adapting screen and font size.Guaranteed to look good on different models
  flutter_screenutil: ^5.9.3
  #A flutter plugin for creating native splash screens for Android and iOS.
  flutter_native_splash: ^2.4.7
  #Flutter widgets for easily adding gaps inside Flex widgets such as Columns and Rows or scrolling views.
  gap: ^3.0.1
  #The Font Awesome Icon pack available as Flutter Icons. Provides 2000 additional icons to use in your apps.
  font_awesome_flutter: ^10.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/
    #- assets/images/splash_screen_android12above.png 

